global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'email-api'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'email-api-golf-battle.railway.internal:8085'
  
  - job_name: 'api-payment'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'api-payment-bb.railway.internal:8080'

  - job_name: 'api-bucket-s3'
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - 'bucket.railway.internal:8080'

  - job_name: 'user-api'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'user-api-golf-battle.railway.internal:8084'
