global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'email-api'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'email-api-golf-battle.railway.internal:8085'

  - job_name: 'user-api'
    metrics_path: /metrics
    authorization:
       type: Bearer
       credentials: 5ea7a26e5b142bde906d6e2c854d395f824d95ac538b3fd08be81d5dbab691d4
    static_configs:
      - targets:
          - 'user-api-golf-battle.railway.internal:8084'
